---
title: "peopleeda"
output: html_document
editor_options: 
  chunk_output_type: console


```{r setup, include=FALSE}
library(tidyverse)
library(forcats)
library(dplyr)
library(stringr)
library(janitor)
library(tidytext)
library(igraph)
library(tidygraph)
library(ggraph)
library(visNetwork)
library(gganimate)
```


```{r}
ratings <- read_csv("../data/IMDbratings.csv")
movies <- read_csv("../data/IMDb movies.csv")
title_principles <- read_csv("../data/IMDb title_principals.csv")
```

```{r}
people <-movies%>%
  mutate(century = case_when(
    year >=2000 ~ "1",
    year>= 900 & year <2000 ~ "0"
  ))  


```

 
### Filtering for most frequent actors by Director Selected.

[ ] A can be renamed to a temporary variable that makes it easier to keep track of the changing dataset. 

[ ] Script for filtering based on director,actor or writer can be a function call. 
```{r}
A<-people%>%
  filter(str_detect(director, "Paul Wegener"))%>%
  select(actors)

names(A)

actors<-unnest_tokens(A, split, names(A), token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(10)

actors$node = replicate(10, "Spike Lee")

actors<-actors%>%
  rename(weight = n)


actorsconnected<-actors%>%
  select(node,split, weight)

B<-people%>%
  filter(director == "Spike Lee")%>%
  select(writer)



writorsconnected<-unnest_tokens(B, split, writer, token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(20)

```


```{r}

bigram_graph<-actorsconnected%>%
  graph_from_data_frame(directed = TRUE)

actorsconnected
name<-"spike lee"

V(bigram_graph)
c(2, actorsconnected$weight)*5

ggraph(bigram_graph,  layout = "kk") +
  geom_edge_link(color = "grey80",
                 aes(width = weight*5), show.legend = FALSE) +
  geom_node_point(size = V(bigram_graph)$weight * 5,
                         aes(color = as.factor(name)),
                         show.legend = FALSE)+
   geom_node_text(aes(label = name), repel=TRUE)+
  theme_graph()+
  scale_color_viridis(discrete = TRUE)+
  transition_components(frame)
  
  
  V(bigram_graph)$color <- (viridis_pal()(11))
  V(bigram_graph)$size  <- 1:11 *5

    visIgraph(bigram_graph, type= "full") %>%
         visInteraction(hover = TRUE, tooltipDelay = 0)
  



connections <- function(centurysel, initialnode, name, connection) { 
if (initialnode == "directors"){
   people%>%
   filter(century == centurysel)%>%
   filter(str_detect(director,  name))%>%
   select(connection) -> A
   top10<-unnest_tokens(A, split, names(A), token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(10)
  top10$node = replicate(10, name)
  top10<-top10%>%
  rename(weight = n)
  top10<-top10%>%
  select(node,split, weight) }
  else {
  if (initialnode == "writer") {
    people%>%
   filter(century == centurysel)%>%
   filter(str_detect(writer,  name))%>%
   select(connection) -> A
   top10<-unnest_tokens(A, split, names(A), token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(10)
  top10$node = replicate(10, name)
  top10<-top10%>%
  rename(weight = n)
  top10<-top10%>%
  select(node,split, weight) }
  else {
  people%>%
   filter(century == centurysel)%>%
   filter(str_detect(actors,  name))%>%
   select(connection) -> A
   top10<-unnest_tokens(A, split, names(A), token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(10)
  top10$node = replicate(10, name)
  top10<-top10%>%
  rename(weight = n)
  top10<-top10%>%
  select(node,split, weight)}}
  return(top10)
  }
  
  
  
  connections("0", "actors", "Spike Lee", "writer")
  
    connections("0", "directors", "Paul Wegener", "actors")
    
   
  
  
  
  A <- people%>%
  filter(century == centurysel)%>%
  filter(director ==  name)%>%
  select(connection)
  
  return(A)
  
  
  top10<-unnest_tokens(A, split, names(A), token = str_split, pattern = ",")%>%
   group_by(split)%>%
  count()%>%
  arrange(desc(n))%>%
  head(10)

top10$node = replicate(10, name)

top10<-top10%>%
  rename(weight = n)


top10<-top10%>%
  select(node,split, weight) 
  
```


## Debugging the first plot.


```{r}
test <- read_csv("../data/test.csv")

 test %>%
         filter(country %in% c("USA", "UK")) %>%
         filter(voter_gender == "F") %>%
         mutate(duration_cat = cut(
            duration,
            breaks = c(-Inf, 41, 151, Inf),
            labels = c(
               "Short Film: <40 mins",
               "Feature Film: 41-150 mins",
               "Long Film: >150 mins"
            )
         )) %>%
         filter(!is.na(voter_gender))%>%
         ggplot(aes(y = avg_vote,
                    x = duration_cat)) +
         geom_violin(fill = "#29AF7F") +
         labs(
            x = "Duration Category",
            y = "Average rating by Males",
            title = "Average IMDb rating by movie duration",
            subtitle = "Faceted by age categories"
         ) +
         facet_wrap(. ~ voter_age)  +
         theme_minimal()
```

